services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: jobs_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www
    container_name: jobs_laravel
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
    - ./tmp/redis:/data
    container_name: jobs_redis


  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lardocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 8101:5432
    container_name: jobs_postgres


